clients:
  university: "http://localhost:8080"
  username: "Bob"
  password: "secret123"

kafka:
  topics:
    student-request: student-info-topic
    student-response: student-async-result

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.IntegerDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      group-id: "learn-aggregator"
      auto-offset-reset: earliest
    properties:
      spring.json.trusted.packages: "*"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.IntegerSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"

jwt:
  config:
    secret: 'c2VjcmV0X3NlY3JldF9zZWNyZXRfc2VjcmV0X3NlY3JldA=='
    tokenExpirationMs: 60_000
    refreshTokenExpirationMs: 3600_000

server:
  port: 8081

logging:
  level:
    org.springframework.boot.context.properties.bind: DEBUG