clients:
  first:
    base-url: "http://localhost:8080"
    username: "user"
    password: "12345"
  service-2: "http://localhost:8081"
  service-3: "http://localhost:8082"

server:
  port: 8081

kafka:
  topics:
    student-request: student-info-topic
    student-response: student-async-result

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.IntegerDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      group-id: "learn-aggregator"
      auto-offset-reset: earliest
    properties:
      spring.json.trusted.packages: "*"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.IntegerSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/learn_base
    username: pg
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true

jwt:
  config:
    secret: 'c2VjcmV0X3NlY3JldF9zZWNyZXRfc2VjcmV0X3NlY3JldA=='
    tokenExpirationMs: 60_000
    refreshTokenExpirationMs: 3600_000